- alias: Turn Off Lights on Plex Play
  trigger:
    - platform: webhook
      webhook_id: plex_event
  condition:
    - condition: template
      value_template: "{{ (trigger.data['payload'] | from_json).event == 'media.play' }}"
    - condition: time
      after: '19:00:00'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen_zone
          - light.main_area
  mode: single

- alias: Brighten Lights on Plex Pause
  trigger:
    - platform: webhook
      webhook_id: plex_event
  condition:
    - condition: template
      value_template: "{{ (trigger.data['payload'] | from_json).event == 'media.pause' }}"
    - condition: time
      after: '19:00:00'
  action:
    - service: light.turn_on
      target:
        entity_id: light.living_room_lamp
      data:
        brightness_pct: 35 # set brightness to 35%
  mode: single

- alias: Turn Off Lights on Plex Resume
  trigger:
    - platform: webhook
      webhook_id: plex_event
  condition:
    - condition: template
      value_template: "{{ (trigger.data['payload'] | from_json).event == 'media.resume' }}"
    - condition: time
      after: '19:00:00'
  action:
    - service: light.turn_off
      target:
        entity_id:
          - light.kitchen_zone
          - light.main_area
  mode: single

- alias: Brighten Lights on Plex Stop
  trigger:
    - platform: webhook
      webhook_id: plex_event
  condition:
    - condition: template
      value_template: "{{ (trigger.data['payload'] | from_json).event == 'media.stop' }}"
    - condition: time
      after: '19:00:00'  # Only trigger after 7 PM
  action:
    - service: light.turn_on
      data:
        entity_id:
          - light.kitchen_zone
          - light.living_room_lamp
        brightness_pct: 35  # set brightness to 35%
        transition: 15  # 30 second fade up
  mode: single


# Debug Automations
#- alias: Turn Off Lights on Plex Play (Debug)
#  trigger:
#    - platform: webhook
#      webhook_id: plex_event
#  action:
#    - service: system_log.write
#      data_template:
#        message: "Plex Webhook Data: {{ trigger.data }}"  # Log the entire payload
#  mode: single
#
#- alias: Brighten Lights on Plex Pause (Debug)
#  trigger:
#    - platform: webhook
#      webhook_id: plex_event
#  action:
#    - service: system_log.write
#      data_template:
#        message: "Plex Webhook Data: {{ trigger.data }}"  # Log the entire payload
#  mode: single
